travis:
  secure:
    BINSTAR_TOKEN: XoJM6gatCpbOaweyj+p09sCu1YH5Yqt+de73/VxtGjY/gKujVnUGZdctnMZOBbET8FQpkq2dyS/nzr7tdf323X9TEvmg2TFsiJjURwyNQGeysB+Ac8muHU65EP94NAp7S+cvLKDn1b9OW7Oh9zUe6DJY+bavxiREMuTcLYFDKeT8z4usAbaC7ZJY1snWLZOThQLK7PWYGgPmvP2KZIL6NiesdytqN9gdykh0oOUpzlOJUkRud2assnPGzkextVrlgeLMfj6Qf967l2+0QMS5Ezlz+ghJtRRNAg24paJfw7bO0d8ilGdYQ7nvgaQv9XmQHJ3l2zCIi+uX8/VuUvxs3JIMqrepD/V9hRGhD+gI29esf5INwQZrbDCkSC0SbgYTiYlBhF16dayHKioCQYSAH5l/d84emdPa5ccI9/FXFxv8QnXvAecjJQTMmcPmva+LN6LzM1g85MIeCsFGWkLXrHuOZoULzRp2SrELmn+wXeRrh43hSIfMjHPzzHJjWrd+oaOBzca/SnF4lM8stsBZ1I9U4oQXsCRSQnrFhhmaw9qk8rRvqGn3XK1tNLyGLSGEjHHN2bzrylAZEfODJ1MJdHrxMUVNogfl54pBxDJwB322UhKogye9gBCmdMKeqhTQkcBx4q5bizDUfq9X/xx+zlbciLhgi9ij2SciKtsVquI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
