travis:
  secure:
    BINSTAR_TOKEN: g4XiIeiZKHbubUChZ2/NNiMq/witFdF1FKrrQ7n1+5GtOohc0fTOu+dqjTDXtdX4aw2MOdIBVbg+FLHEE0VHd+pbjAhQjoBJwhyROnfXCWk7j4qKM+U6FMxsq0ZUaYvO8inPGC+XaANIfr3JgYty1EbfRQZEnhmhFQan2ENL5+WZbdw8LJyAT+eU7cqTtWVQrNNfy3RIl8dBiLw539Z/PeQUBIu3L6H0VKjr4skgbrfwOh98fS9Ue2Hor0o64O9ytkL1M7qK1L5erteGNZZNgtlWpVhlK6+XFA++o/NNTeaTvRlEkWFX6wMUWvrfXMJ6DmVdhqMnRaP4O50bSL2dmDICOOUnnGXNCLHei4cNK46Hp0JbdrRW2PZz6E8g2T0KPhJG+7frw/Jo59UJYh6+qI5EX4RUKL93D0qjAE2h36eGFDRJCTO/5Iu0kXQ4YROhgwu8UJnKxY1qzB1vSnEgkcPTA0eS83Wf9rJtmOcqWV0P3DksXuPRbOGsyxuut2rqXFbxMfAma1VrWlpELaUsbI423wLZYGFGgB1bLe016peeSz51KoNVRPAxkVF/DXuFc46FH+J4xjcUJRnXs/hBrbMigGmiP0pscXkYqWLLTsoq4hFHBXNBVCxqOTyGqpzt9l2rhWbjnJGchk3HBn7MaMiJFzo8dMHmNu4tkVOgeqo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
