travis:
  secure:
    BINSTAR_TOKEN: vxd8v+pSYl9fHBs4lvbIYkFsdjhSxwXt0ZisUY61Xs4nEYLOsHNTSe4/pNW0tUncjPoKhqTnytewkCqVH60pz4w/c48jONKX08i6yKu4Sskc3TULfoQmoEYDfT5+ToGp77/1bYcHEx46hs/eeyPeau6uLA/xCnNVhkjLFel5PMxLhLWMF/A8T/3Fa4K0xmm2kXEUoVOCtiZQTrvzvwX/MDY4F4mA9D6TKTMC2SnGSJvM1eWm6EgeHWGfMpY+e+MIH3b1K6aHglg0zKbdJ0mPZqcG0tVB9ePDZGmEp7SGqIeSAtQjGtmvlfrrHZXyURDixmyRhuoupNafQ8lEFX84eKzTSOLlsehsGti0G2TxU6CKgV8mc92rVO6Ya0B2yY8s6cNGytNVvAmzdSchPo34jtKcdEBI3qyPyFByBn2zHvqVxnUOfP24qSfJJ2WFyaz/+Qco7F89brRidpYIeb6c4tjTjiJ03oMtDMMmTYo+WHDRb7Frnx8gwSBIMPXKWW/Qi7jpARuf6sNyXFm1VHzZs2xnywkSmdNXili4325iQZA2+wB88z+bRUJantAqGygB4ME3Ss2yWfT0/gG2SsaVpyALkqTE/kVpSIYulmgIhYVstmpIwbjgd4o2NOZODJ5hxgW/xcvJL/9JP9sijX8nv12tN4ocadIaz6oK3JtGsfA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
